name: remote ssh command


on:
  push:
    branches:
    - dev
jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: build and run docker image 
      run: git pull && docker-compose up -d --build
